services:
  - type: web
    name: cordly-ai-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: cordly-ai-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: False
      - key: PYTHONUNBUFFERED
        value: 1

databases:
  - name: cordly-ai-db
    databaseName: cordly_ai
    user: cordly_ai_user
    plan: free
    region: singapore